name              = "rpi-sentinel-worker"
main              = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding       = "DB"
database_name = "rpi-sentinel-db"
# Replace with the ID returned by: wrangler d1 create rpi-sentinel-db
database_id   = "2c0a43bb-a601-466a-b738-4ec30cecb096"
